jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0   # 必须加，不然 notes-from-tag 找不到 tag
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.13"
      - name: Bundle
        run: |
          uv tool run hatch build --target wheel
      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}
        run: |
          gh release create v${TAG} \
            --title "yt-dlp-ejs v${TAG}" \
            --notes-from-tag \
            --verify-tag \
            dist/yt.solver.* \
            dist/yt_dlp_ejs*.whl
